### ISSUE TITLE
关于多对多

### ISSUE THREAD

**Issue by NYF828** [GreedyStar/generator#8]
多对多为什么只生成一个

**Comment by GreedyStar** [comment]
由于生成的源码文件是直接写入项目所在路径的文件系统中，所以在编译器中可能会出现没有及时读取到源码文件的现象，出现这种情况只需要重新打开项目即可。

**Comment by GreedyStar** [comment]
> 多对多为什么只生成一个
由于生成的源码文件是直接写入项目所在路径的文件系统中，所以在编译器中可能会出现没有及时读取到源码文件的现象，出现这种情况只需要重新打开项目即可。

**Comment by GreedyStar** [comment]
> 多对多为什么只生成一个

由于生成的源码文件是直接写入项目所在路径的文件系统中，所以在编译器中可能会出现没有及时读取到源码文件的现象，出现这种情况只需要重启编译器即可。
